INSERT INTO `def_changelog` (`id`, `message`, `version`, `major`, `date`) VALUES
  (1, '<ul><li>Ability to set how many items are displayed in data grids. Visit your <a href="{plink Default:settings}">account settings</a> now.</li><li><a href="{plink Director:default}">Director list</a> offers more information.</li><li>Improvements in forms, selectboxes now offer live search.</li></ul>', '0.1', 1, '2016-09-29'),
  (2, '<ul><li>Added ''Men''s Rating'' and ''Women''s Rating'' columns which calculate average rating by gender.</li><li>Added column ''Czech Title''.</li><li>Description is no longer required.</li><li>Choosing director from selectbox disables director-related inputs.</li></ul>', '0.2', 1, '2016-11-26'),
  (3, '<ul><li>Added option to add/edit director.</li><li>Added option to edit movie details.</li><li>Migrated to Nette 2.4.</li><li>Some other technical improvements.</li></ul>', '0.3', 1, '2016-11-28'),
  (4, '<ul><li>Added outline to paginator.</li></ul>', '0.3.1', 0, '2016-11-29'),
  (5, '<ul><li>JS dependencies are managed using bower.</li><li>Resolved some bugs.</li></ul>', '0.3.2', 0, '2016-11-30'),
  (6, '<ul><li>Changed movie default page.</li></ul>', '0.4', 1, '2016-12-02'),
  (7, '<ul><li>Added support for multiple directors.</li><li>Added user activity statistics.</li></ul>', '0.5', 1, '2016-12-03'),
  (8, '<ul><li>Added option to save actors.</li><li>Added AJAX subform for adding new person.</li><li>Added acting information to person page.</li></ul>', '0.6', 1, '2016-12-04'),
  (9, '<ul><li>Director list doesn''t display other people.</li></ul>', '0.6.1', 0, '2016-12-05'),
  (10, '<ul><li>Added movie actor list.</li><li>Moved changelog and credits to standalone page.</li></ul>', '0.7', 1, '2016-12-06'),
  (11, '<ul><li>Added books.</li><li>Many bug fixes and other technical improvements.</li></ul>', '0.8', 1, '2016-12-09'),
  (12, '<ul><li>Added pseudonyms.</li><li>Better error messages in forms.</li><li>Fixes in entity form.</li></ul>', '0.9', 1, '2016-12-10'),
  (13, '<ul><li>Added music.</li><li>Added more information to person, psudonym and band pages.</li></ul>', '0.10', 1, '2016-12-12'),
  (14, '<ul><li>Reworked subforms in entity form.</li><li>Flash messages fade out</li><li>Some technical imporovements.</li></ul>', '0.10.1', 0, '2016-12-18'),
  (15, '<ul><li>Added dropdown sections to navbar.</li><li>Many fixes and technical improvements.</li></ul>', '0.10.2', 0, '2016-12-22'),
  (16, '<ul><li>Added global search.</li></ul>', '0.11', 1, '2016-12-23'),
  (17, '<ul><li>Tehnical improvements and fixes.</li></ul>', '0.11.1', 0, '2016-12-24'),
  (18, '<ul><li>Added series.</li><li>Enhanced rating form.</li></ul>', '0.12', 1, '2017-01-12'),
  (19, '<ul><li>Added seasons.</li></ul>', '0.13', 1, '2017-01-22'),
  (20, '<ul><li>Added games.</li></ul>', '0.14', 1, '2017-02-05'),
  (21,'<ul><li>Enabled some sorting options.</li><li>Fixed various bugs with pseudonyms.</li></ul>', '0.14.1', 0, '2017-02-19'),
  (22, '<ul><li>Added charts to statistics.</li><li>Added user activity radar chart.</ul>', '0.15', 1, '2017-02-25'),
  (23, '<ul><li>Added radar chart to activity table.</li><li>Small fixes and improvements.</ul>', '0.15.1', 0, '2017-03-01');
